site_name: Docker para Desarrolladores
nav:
  - Introducción : 1_introduccion.md
  - Arquitecturas de Microservicios: 2_arquitecturas_de_microservicios.md
  - Construcción de imágenes: 3_construccion_de_imagenes.md
  - Desarrollo con contenedores: 4_desarrollo_con_contenedores.md
  - Integración continua: 5_integracion_continua.md
  - Docker en producción: 6_docker_en_produccion.md
theme: readthedocs

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: es
